PRODUCT_MATERIAL_CODES = {
    "FG-RAMEN": ("RM-NOODLE", "RM-SOUP-REGULAR", "RM-PACK-REGULAR"),
    "FG-SPICY": ("RM-NOODLE", "RM-SOUP-SPICY", "RM-PACK-SPICY"),
    "FG-MILD": ("RM-NOODLE", "RM-SOUP-MILD", "RM-PACK-MILD"),
}
MATERIAL_ITEM_CODES = tuple(
    dict.fromkeys(
        material_code
        for recipe in PRODUCT_MATERIAL_CODES.values()
        for material_code in recipe
    )
)
BOX_SIZE = 40
RAW_MATERIAL_SAFETY_STOCK = 500
PACKAGING_CAPACITY_PER_MINUTE = 1

DEMO_REQUEST_QUANTITY = 1_000
DEMO_REQUEST_COUNT = 3
DEMO_SHIPMENT_QUANTITY = 800
